### ISSUE TITLE
Tempo fails to start - span_metrics field not found in generator.Config

### ISSUE THREAD

**Issue by CodeWithDuke** [saidsef/grafana-loki-on-k8s#141]
Hello Said, I hope you're doing well

**Description**
After updating to the latest main branch, Tempo is failing to start with the following error:

```
failed parsing config: failed to parse configFile /conf/tempo.yaml: yaml: unmarshal errors:
line 19: field span_metrics not found in type generator.Config
```

**Configuration**
The issue appears to be with the placement of the span_metrics field in the configuration. It's currently placed directly under metrics_generator but needs to be under metrics_generator.processor.

**Fix**
Moving span_metrics to be nested under the processor section resolves the issue:
yamlmetrics_generator:

  processor:
```
    local_blocks:
      filter_server_spans: false
    service_graphs:
      enable_client_server_prefix: true
      enable_virtual_node_label: true
    span_metrics:  # Correctly placed under processor
      enable_target_info: true

```
**Environment**

Latest main branch
Local development environment docker and docker desktop k8s version 1.29.2
